apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-sink-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kafka-sink
  name: kafka-sink
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-sink
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-sink
    spec:
      containers:
        - name: kafka-sink
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap.kafka:9092"
            - name: KAFKA_TOPIC
              value: "my-sink-topic"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-sink
spec:
  selector:
    app.kubernetes.io/name: kafka-sink
  ports:
    - name: http
      port: 80
      targetPort: 8080
